config/routes.rb
Booking::Application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  resources :users, only: [:show]

  resources :cities do
    resources :playgrounds, constraints: {city_id: /[0-9]+/}, shallow: true
  end

  resources :playgrounds do
    resources :reviews, constraints: {playground_id: /[0-9]+/}, shallow: true do
      collection do
        get 'more'
      end
    end
  end

  resources :playgrounds do
    resources :calendars, shallow: true
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  belongs_to :playground, inverse_of: :calendars
  belongs_to :user, inverse_of: :calendars
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :regions, dependent: :destroy
  has_many :playgrounds

  validates :name, presence: true

end

app/models/cover.rb
class Cover < ActiveRecord::Base
  validates :name, presence: true
end

app/models/infrastructure.rb
class Infrastructure < ActiveRecord::Base
  has_and_belongs_to_many :playgrounds
  validates :name, presence: true
end

app/models/media_gallery.rb
class MediaGallery < ActiveRecord::Base

  has_many :media_medias, autosave: true, dependent: :destroy, inverse_of: :media_gallery
  belongs_to :playground

  accepts_nested_attributes_for :media_medias, :allow_destroy => true
end

app/models/media_media.rb
class MediaMedia < ActiveRecord::Base
  belongs_to :media_gallery, inverse_of: :media_medias
  has_attached_file :file, styles: {medium: "1000x400#", list: "455x325#", thumb: "300x200#"}, default_url: "/assets/medium/missing.png",
                    :path => ":rails_root/public/:url",
                    :url => "/system/:class/:id/:id_partition/:style/:normalized_file_file_name.:extension"

  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/

  Paperclip.interpolates :normalized_file_file_name do |attachment, style|
    attachment.instance.normalized_file_file_name
  end

  def normalized_file_file_name
    "#{self.id}#{self.file_file_name.gsub(/[^a-zA-Z0-9_\.]/, '_')}"
  end
end

app/models/playground.rb
class Playground < ActiveRecord::Base
  belongs_to :region, :autosave => true
  belongs_to :city
  belongs_to :roof
  belongs_to :cover
  belongs_to :sport_type
  has_many :reviews, inverse_of: :playground
  has_many :calendars, inverse_of: :playground
  has_and_belongs_to_many :infrastructures
  has_one :media_gallery, dependent: :destroy, inverse_of: :playground
  validates_associated :region, :roof, :cover, :sport_type
  validates :name, length: {minimum: 1}
  validates :name, presence: true
  accepts_nested_attributes_for :media_gallery

end

app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :city
  has_many :playgrounds
  validates :name, :city_id, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :playground

  validates_associated :playground
end

app/models/roof.rb
class Roof < ActiveRecord::Base

  validates :name, presence: true
end

app/models/sport_type.rb
class SportType < ActiveRecord::Base
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :calendars, inverse_of: :user

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.username = auth.info.username
      #user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    respond_to do |format|
      format.json { render json: City.all }
    end
  end

  def show
    respond_to do |format|
      format.json { render json: City.find(params[:id]) }
      format.xml { render xml: City.find(params[:id]) }
    end
  end
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController
  def index
    @city = City.find(params[:city_id])
    @infrastructures = Infrastructure.all
    @covers = Cover.all

    @playgrounds = @city.playgrounds
    @playgrounds = @playgrounds.joins(:roof).where("roof_id = ?", params[:roof][:id]) if params.include? 'roof'
    @playgrounds = @playgrounds.joins(:infrastructures).where(:infrastructures => params[:infrastructure]) if params.include? 'infrastructure'

    #@playgrounds = @playgrounds.joins(:cover).find(cover_id:params[:cover][:id]) if params.include?'cover'
    respond_to do |format|
      format.html
      format.json { render json: @playgrounds }
      format.xml { render xml: @playgrounds }
    end
  end

  def show
    @playground = Playground.find(params[:id])
    @reviews = @playground.reviews.order(created_at: :desc).limit(4)
    @similar = Playground.all.limit(4)
    respond_to do |format|
      format.html
      format.json { render json: @playground }
      format.xml { render xml: @playground }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.create(review_params)
    redirect_to :back, status: 301
  end

  def index
    respond_to do |format|
      format.json { render json: Playground.find(params[:playground_id]).reviews }
    end
  end

  def review_params
    params.require(:review).permit(:personal_rating, :location_rating, :infrastructure_rating, :field_rating, :cover_description, :general_impression, :infrastructure_description, :playground_id)
  end

  def more
    @reviews = Review.order(:created_at => :desc).offset(params[:offset]).limit(10)
    render :partial => 'reviews/more'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user =User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/playgrounds/_filters.html.erb
<div class="well">
  <%= form_for(:playground, method: 'get') do %>
      <div class="form-group">
        <h5><%= I18n.t 'title_time' %></h5>
        <%= text_field(:playground, :start_time, {value: '07:00', type: 'time'}) %>
        <%= text_field(:playground, :end_time, {value: '23:59', type: 'time'}) %>
        <input type="text" class="slider-time" value=""
               data-slider-min="0"
               data-slider-max="24"
               data-slider-step="1"
               data-slider-value="[7,10 ]"
               data-slider-orientation="horizontal"
               data-slider-selection="after"
               data-slider-tooltip="show">
      </div>
      <hr/>
      <div class="form-group">
        <h5><%= I18n.t 'price' %></h5>
        <%= text_field(:playground, :min_price, {value: '0', type: 'number'}) %>
        <%= text_field(:playground, :max_price, {value: '2000', type: 'number'}) %>
        <input type="text" class="slider-price" value=""
               data-slider-min="0"
               data-slider-max="2000"
               data-slider-step="50"
               data-slider-value="[0,2000]"
               data-slider-orientation="horizontal"
               data-slider-selection="after"
               data-slider-tooltip="show">
      </div>

      <hr/>
      <div class="form-group roof">
        <h5><%= I18n.t 'roof' %></h5>
        <%= collection_radio_buttons(:roof, :id, Roof.all, :id, :name) %>
      </div>

      <hr/>
      <div class="form-group infrastructure">
        <h5><%= I18n.t 'infrastructure' %></h5>
        <%= collection_check_boxes(:infrastructure, :id, Infrastructure.all, :id, :name) %>
      </div>
      <hr/>
      <div class="form-group cover">
        <h5><%= I18n.t 'cover' %></h5>
        <%= collection_check_boxes(:cover, :id, Cover.all, :id, :name) %>
      </div>
  <% end %>
</div>

app/views/playgrounds/_similar.html.erb
<div class="row p-similar">
  <% @similar.each do |p| %>
      <% unless p.media_gallery.is_a? NilClass %>
          <div><%= link_to(image_tag(p.media_gallery.media_medias.first.file.url(:thumb)), playground_path(p)) %></div>
      <% end %>
  <% end %>
</div>

app/views/playgrounds/index.html.erb
<div class="row p-list">
  <% @playgrounds.each do |playground| %>
      <div class="col-md-6 p-item">
        <%= link_to playground_path(playground), class: 'itm-link' do %>
            <%= image_tag playground.media_gallery.media_medias.first.file.url(:list) %>
            <p>
              <%= playground.name %>,<%= playground.sport_type.name %><br/>
              <span class="text-muted"><%= playground.region.name %>, <%= playground.address %></span>
            </p>

            <div class="item-price">
              <%= playground.min_price.to_i %>
              <span class="price-currency"><%= t('currency.som').to_s %></span>
            </div>
        <% end %>
      </div>
  <% end %>
</div>

app/views/playgrounds/show.html.erb
<!--YIELD Average Rating-->
<%= content_for :avg_rating do %>
    <% if @playground.reviews.length > 0 %><%= (@playground.reviews.average('personal_rating')+@playground.reviews.average('location_rating')+@playground.reviews.average('infrastructure_rating')+@playground.reviews.average('field_rating'))/4 %>
    <% end %>
<% end %>

<!--Image Gallery-->
<div class="row g-parent">
  <div class="r-gallery">
    <% @playground.media_gallery.media_medias.each do |media| %>
        <div><%= image_tag media.file.url(:medium) %></div>
    <% end %>
  </div>
</div>
<!--END Image Gallery-->

<!--Field Summary-->
<div class="row p-summary">
  <h4><%= @playground.name %></h4>

  <!--Total average rating-->
  <p class="text-muted"><%= @playground.region.name %>
    , <%= @playground.address %> &nbsp; <span class="n-raty" data-raty="<%= yield :avg_rating %>"></span>
    (<%= @playground.reviews.length %>)
  </p>
  <% @playground.infrastructures.each do |i| %>
      <span class="inf inf-<%= i.icon %>"></span>
      <%= i.name %>
  <% end %>
  <div class="p-price">
    <%= @playground.min_price %> <%= t('currency.som') %>
  </div>
</div>
<!--END Field Summary-->


<div class="row p-properties">
  <div class="col-md-7">
    <div class="row">
      <p class="col-md-3"><%= t('activerecord.models.sport_type') %>:</p>

      <p class="col-md-9"><%= @playground.sport_type.name %></p>
    </div>
    <div class="row">
      <p class="col-md-3"><%= t('activerecord.attributes.playground.size') %>:</p>

      <p class="col-md-9"><%= @playground.size %></p>
    </div>
    <div class="row">
      <p class="col-md-3"><%= t('activerecord.attributes.playground.max_players') %>:</p>

      <p class="col-md-9"><%= @playground.max_players %></p>
    </div>
    <div class="row">
      <p class="col-md-3"><%= t('roof') %>:</p>

      <p class="col-md-9"><%= @playground.roof.name %></p>
    </div>
    <div class="row">
      <p class="col-md-3"><%= t('activerecord.models.cover') %>:</p>

      <p class="col-md-9"><%= @playground.cover.name %></p>
    </div>
    <div class="row">
      <p class="col-md-3">Инфраструктура:</p>

      <p class="col-md-9">
        <% @playground.infrastructures.each do |infrastructure| %>
            <%= infrastructure.name %>
        <% end %>
      </p>

    </div>
  </div>
  <div class="col-md-5 p-about">
    <h4><%= t('about') %></h4>

    <p><%= @playground.description %></p>
  </div>
</div>

<!--Reviews-->
<div class="row">
  <div class="col-md-9 bg-white reviews">
    <div>
      <div class="review-head">
        <h4 class="pull-left"><%= t('activerecord.attributes.playground.reviews') %>

          <!--Total average rating-->
          <span class="n-raty" data-raty="<%= yield :avg_rating %>"></span>
          (<%= @playground.reviews.length %>)
        </h4>
        <button class="btn btn-success pull-right" data-toggle="modal" data-target="#reviewModal"><%= t('writereview') %></button>
      </div>
      <%= render 'reviews/list' %>
      <%= render 'reviews/new' %>
    </div>
  </div>
  <div class="col-md-3 bg-white">

    <%= link_to playground_calendars_url playground_id: @playground.id do %>
        <button class="btn btn-danger pull-right">
          <%= t('go.schedule') %>
        </button>
    <% end %>
  </div>
</div>
<!--END Reviews-->

<%= render 'similar' %>