config/routes.rb
Booking::Application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

  resources :users, only: [:show]

  resources :cities do
    resources :playgrounds, constraints: {city_id: /[0-9]+/}, shallow: true
  end

  resources :playgrounds do
    resources :reviews, constraints: {playground_id: /[0-9]+/}, shallow: true do
      collection do
        get 'more'
      end
    end
  end

  resources :playgrounds do
    resources :calendars, shallow: true
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  belongs_to :playground, inverse_of: :calendars
  belongs_to :user, inverse_of: :calendars
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :regions, dependent: :destroy
  has_many :playgrounds

  validates :name, presence: true

end

app/models/cover.rb
class Cover < ActiveRecord::Base
  validates :name, presence: true
end

app/models/infrastructure.rb
class Infrastructure < ActiveRecord::Base
  has_and_belongs_to_many :playgrounds
  validates :name, presence: true
end

app/models/media_gallery.rb
class MediaGallery < ActiveRecord::Base

  has_many :media_medias, autosave: true, dependent: :destroy, inverse_of: :media_gallery
  belongs_to :playground

  accepts_nested_attributes_for :media_medias, :allow_destroy => true
end

app/models/media_media.rb
class MediaMedia < ActiveRecord::Base
  belongs_to :media_gallery, inverse_of: :media_medias
  has_attached_file :file, styles: {medium: "1000x400#", list: "455x325#", thumb: "300x200#"}, default_url: "/assets/medium/missing.png",
                    :path => ":rails_root/public/:url",
                    :url => "/system/:class/:id/:id_partition/:style/:normalized_file_file_name.:extension"

  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/

  Paperclip.interpolates :normalized_file_file_name do |attachment, style|
    attachment.instance.normalized_file_file_name
  end

  def normalized_file_file_name
    "#{self.id}#{self.file_file_name.gsub(/[^a-zA-Z0-9_\.]/, '_')}"
  end
end

app/models/playground.rb
class Playground < ActiveRecord::Base
  belongs_to :region, :autosave => true
  belongs_to :city
  belongs_to :roof
  belongs_to :cover
  belongs_to :sport_type
  has_many :reviews, inverse_of: :playground
  has_many :calendars, inverse_of: :playground
  has_and_belongs_to_many :infrastructures
  has_one :media_gallery, dependent: :destroy, inverse_of: :playground
  validates_associated :region, :roof, :cover, :sport_type
  validates :name, length: {minimum: 1}
  validates :name, presence: true
  accepts_nested_attributes_for :media_gallery

end

app/models/region.rb
class Region < ActiveRecord::Base
  belongs_to :city
  has_many :playgrounds
  validates :name, :city_id, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :playground

  validates_associated :playground
end

app/models/roof.rb
class Roof < ActiveRecord::Base

  validates :name, presence: true
end

app/models/sport_type.rb
class SportType < ActiveRecord::Base
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :calendars, inverse_of: :user

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.username = auth.info.username
      #user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    respond_to do |format|
      format.json { render json: City.all }
    end
  end

  def show
    respond_to do |format|
      format.json { render json: City.find(params[:id]) }
      format.xml { render xml: City.find(params[:id]) }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.create(review_params)
    redirect_to :back, status: 301
  end

  def index
    respond_to do |format|
      format.json { render json: Playground.find(params[:playground_id]).reviews }
    end
  end

  def review_params
    params.require(:review).permit(:personal_rating, :location_rating, :infrastructure_rating, :field_rating, :cover_description, :general_impression, :infrastructure_description, :playground_id)
  end

  def more
    @reviews = Review.order(:created_at => :desc).offset(params[:offset]).limit(10)
    render :partial => 'reviews/more'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user =User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/_menu.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
      <li>
        <%= link_to current_user do %>
            <% if current_user.uid %>
                <%= image_tag "http://graph.facebook.com/#{current_user.uid}/picture", {:class => 'profile-icon img-rounded'} %>
            <% end %>
            <%= current_user.first_name %>
        <% end %>
      </li>
      <li>
        <%= link_to edit_user_registration_path, {:data => {:toggle => :tooltip, :placement => :bottom}, :title => t('devise.settings')} do %>
            <i class="fa fa-lg fa-gear"></i>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, {:method => :delete, :data => {:toggle => :tooltip, :placement => :left}, :title => I18n.t('devise.sign.out')} do %>
            <i class="fa fa-sign-out fa-lg"></i>
        <% end %>
      </li>
  <% else %>
      <li><%= link_to new_user_session_path do %>
            <i class="fa fa-sign-in fa-lg"></i>
            <%= t('devise.sign.in') %>
        <% end %></li>
  <% end %>
</ul>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
        <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end -%>
<% end -%>

app/views/users/show.html.erb
<%= @user.first_name %>